
parameters:
    chebur.login_form.form.helper.class: Chebur\LoginFormBundle\Security\Form\LoginFormHelper

services:
    chebur.login_form.authentication.listener:
        class: Chebur\LoginFormBundle\Security\Http\Firewall\LoginFormAuthenticationListener
        parent: 'security.authentication.listener.abstract'
        public: false
        abstract: true

    chebur.login_form.form.helper:
        class: '%chebur.login_form.form.helper.class%'
        arguments:
            - '@security.authentication_utils'
            - '@translator'
